/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Musicextras");
gchar *s = N_("Main Window");
gchar *s = N_("<b>Album Cover</b>");
gchar *s = N_("<b>Artist Image</b>");
gchar *s = N_("Show more information");
gchar *s = N_("_More Information");
gchar *s = N_("Edit the lyrics");
gchar *s = N_("_Edit");
gchar *s = N_("Send new song information");
gchar *s = N_("_Change Song");
gchar *s = N_("More Information");
gchar *s = N_("Biography");
gchar *s = N_("Album Review");
gchar *s = N_("Change Song");
gchar *s = N_("_Fill From File");
gchar *s = N_("<b>Song Information</b>");
gchar *s = N_("    ");
gchar *s = N_("Artist:");
gchar *s = N_("Title:");
gchar *s = N_("Album:");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
