require 'musicextras/musicsites/allmusic.rb'
require 'musicextras/musicsites/lyricsnet.rb'
require 'musicextras/musicsites/lyricstime.rb'
require 'musicextras/musicsites/plyrics.rb'
require 'musicextras/musicsites/atame.rb'
require 'musicextras/musicsites/allofmp3.rb'
